### ISSUE TITLE
how to generate coarse WSE based on coarse WSH and fine DEM

### ISSUE THREAD

**Issue by rumeitang** [cefect/FloodRescaler#12]
Hi, now I have fine DEM and coarse WSH. How should I generate a coarse WSE to use as input for your algorithm? Is it correct to upscale the DEM and then add it to the WSH? Thank you in advance for your support.

**Comment by cefect** [comment]
Thank you for the question. If I understand the question, you're trying to convert a coarse WSH to a coarse WSE using a fine DEM. In general, this requires two basic steps 1) DEM + WSH; 2) set mask from WSH<=0. At some point I'll add this tool to the project. 

As for which DEM to use: ideally, this should be the same DEM used to generate the WSH in the first place (e.g., whatever DEM was fed to your hydrodynamic model). If this original coarse DEM is not available, you could try to re-create it from your fine DEM through resampling (e.g., [average resampling](https://gdal.org/programs/gdalwarp.html#cmdoption-gdalwarp-r)). However, this will likely introduce some mismatch/artifacts in the resulting coarse WSE which may or may not be acceptable. 

Hope this helps,

**Comment by rumeitang** [comment]
Thanks for your response. However, it seems that I've encountered an new issue during the 'isolated filter' step. What could be a possible solution?

isolated filter==============================================

processing 1=wet 0=dry WSE mask for WBT
GDAL command:
gdal_calc.bat --overwrite --calc "A/A" --format netCDF --type Float32 --NoDataValue -9999.0 -A C:\Users\19107\AppData\Local\Temp\tmpl9pn0jcg\05bdem_mask.tif --A_band 1 --outfile C:/Users/19107/AppData/Local/Temp/processing_xmPXoX/71567c8162904bc497700341ede4e71b/OUTPUT.nc
GDAL command output:
<string>:1: RuntimeWarning: invalid value encountered in divide
0...10...20...30...40...50...60...70...80...90...100 - done.
Process completed successfully
Results: {'OUTPUT': 'C:/Users/19107/AppData/Local/Temp/processing_xmPXoX/71567c8162904bc497700341ede4e71b/OUTPUT.nc'}
Results: {'OUTPUT': 'C:\\Users\\19107\\AppData\\Local\\Temp\\tmpl9pn0jcg\\filter_isolated\\01_WSEmask_f4yzhird.tif'}

processing clump mosaic from WSE mask
WhiteboxTools command:
"D:/WBT/whitebox_tools.exe" -v=true --compress_rasters=True --max_procs=12 --run=Clump --input="C:\Users\19107\AppData\Local\Temp\tmpl9pn0jcg\filter_isolated\01_WSEmask_f4yzhird.tif" --diag="False" --zero_back="True" --output="C:\Users\19107\AppData\Local\Temp\tmpl9pn0jcg\filter_isolated\02_clumps_k3yx23_6.tif"
WhiteboxTools output:
****************************
* Welcome to Clump *
* Powered by WhiteboxTools *
* www.whiteboxgeo.com *
****************************
Reading data...
thread 'main' panicked at 'The TIFF file does not contain geokeys', whitebox-tools-app\src\main.rs:72:21
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
Process returned error code 101
Results: {'output': 'C:\\Users\\19107\\AppData\\Local\\Temp\\tmpl9pn0jcg\\filter_isolated\\02_clumps_k3yx23_6.tif'}
Unable to execute algorithm
Could not load source layer for input: C:\Users\19107\AppData\Local\Temp\tmpl9pn0jcg\filter_isolated\02_clumps_k3yx23_6.tif not found
Unable to execute algorithm
Could not load source layer for input: C:\Users\19107\AppData\Local\Temp\tmpl9pn0jcg\filter_isolated\02_clumps_k3yx23_6.tif not found
Execution failed after 4.58 seconds

**Comment by cefect** [comment]
created separate issue
