### ISSUE TITLE
gdal_calc:  RuntimeWarning: invalid value encountered in divide

### ISSUE THREAD

**Issue by cefect** [cefect/FloodRescaler#13]
Thanks for your response. However, it seems that I've encountered an new issue during the 'isolated filter' step. What could be a possible solution?

> 
> isolated filter==============================================
> 
> processing 1=wet 0=dry WSE mask for WBT
> GDAL command:
> gdal_calc.bat --overwrite --calc "A/A" --format netCDF --type Float32 --NoDataValue -9999.0 -A C:\Users\19107\AppData\Local\Temp\tmpl9pn0jcg\05bdem_mask.tif --A_band 1 --outfile C:/Users/19107/AppData/Local/Temp/processing_xmPXoX/71567c8162904bc497700341ede4e71b/OUTPUT.nc
> GDAL command output:
> <string>:1: RuntimeWarning: invalid value encountered in divide
> 0...10...20...30...40...50...60...70...80...90...100 - done.
> Process completed successfully
> Results: {'OUTPUT': 'C:/Users/19107/AppData/Local/Temp/processing_xmPXoX/71567c8162904bc497700341ede4e71b/OUTPUT.nc'}
> Results: {'OUTPUT': 'C:\\Users\\19107\\AppData\\Local\\Temp\\tmpl9pn0jcg\\filter_isolated\\01_WSEmask_f4yzhird.tif'}
> 
> processing clump mosaic from WSE mask
> WhiteboxTools command:
> "D:/WBT/whitebox_tools.exe" -v=true --compress_rasters=True --max_procs=12 --run=Clump --input="C:\Users\19107\AppData\Local\Temp\tmpl9pn0jcg\filter_isolated\01_WSEmask_f4yzhird.tif" --diag="False" --zero_back="True" --output="C:\Users\19107\AppData\Local\Temp\tmpl9pn0jcg\filter_isolated\02_clumps_k3yx23_6.tif"
> WhiteboxTools output:
> ****************************
> * Welcome to Clump *
> * Powered by WhiteboxTools *
> * www.whiteboxgeo.com *
> ****************************
> Reading data...
> thread 'main' panicked at 'The TIFF file does not contain geokeys', whitebox-tools-app\src\main.rs:72:21
> note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
> Process returned error code 101
> Results: {'output': 'C:\\Users\\19107\\AppData\\Local\\Temp\\tmpl9pn0jcg\\filter_isolated\\02_clumps_k3yx23_6.tif'}
> Unable to execute algorithm
> Could not load source layer for input: C:\Users\19107\AppData\Local\Temp\tmpl9pn0jcg\filter_isolated\02_clumps_k3yx23_6.tif not found
> Unable to execute algorithm
> Could not load source layer for input: C:\Users\19107\AppData\Local\Temp\tmpl9pn0jcg\filter_isolated\02_clumps_k3yx23_6.tif not found
> Execution failed after 4.58 seconds

_Originally posted by @rumeitang in https://github.com/cefect/FloodRescaler/issues/12#issuecomment-1890941993_

**Comment by cefect** [comment]
it looks like there is an issue with converting the downscaled output WSE into a binary inundation raster (gdal_calc --A/A). I would try starting with a very small test area, and seeing if you can reproduce the issue. If this doesn't solve the problem, please send the input files and the logs and I can take a look.

good luck! @rumeitang

**Comment by rumeitang** [comment]
[inputs&log.zip](https://github.com/cefect/FloodRescaler/files/13936148/inputs.log.zip)
Here are the input files and the log for your reference.

**Comment by cefect** [comment]
Thank you for the input data. Contrary to my first guess, this doesn't seem to be a 'divide by zero' issue, but a limitation of the clump selection (i.e. isolated filter). This shows the clumps:
![image](https://github.com/cefect/FloodRescaler/assets/47092034/b014ba8e-dadb-4825-a170-8079b5856e46)

in the current version, the largest clump is simply selected (which in your case is the NE purple blob).  On my to-do  list is to implement the more sophisticated pixel-selection from [the pure-python version](https://github.com/cefect/FloodDownscaler2). 

as a workaround, you could do one of the following:

- manually finish the algorithm starting from the isolated filter step (selecting all of the clumps you're interested in)
- temporarily edit [this line](https://github.com/cefect/FloodRescaler/blob/c2608dda265bc613f945be7c428aa5effa0d0258/floodrescaler/processing/dscale.py#L505) to point to a manually created raster mask that includes all the clumps you're interested in
- pre-process the DEM to mask out the problematic regions (this will be challenging in your case as the downscaled result is also discontinuous) 

Hopefully I can implement a more permanent fix soon

**Comment by cefect** [comment]
@rumeitang, try using the new 'pixel' based method I just pushed. This should give you some reasonable results in the upper part of your reach (the lower part is quite flat and there is no obvious floodplain). 
![image](https://github.com/cefect/FloodRescaler/assets/47092034/3de6145d-0ffc-4f14-bf3b-ee436cf96dec)
