### ISSUE TITLE
Pixel based tool

### ISSUE THREAD

**Issue by AnuPal1Hydro123** [cefect/FloodRescaler#15]
Hi

Is the new pixel-based tool for binary  flood maps?

**Comment by cefect** [comment]
No, this is a more accurate method for the 'isolated filter' step. See the description [here](https://github.com/cefect/FloodRescaler/blob/d5c56a32e9a55efefbfe1e7b524474df59066b9e/floodrescaler/processing/dscale.py#L128) and my response to your previous question [here](https://github.com/cefect/FloodRescaler/issues/9).
