### ISSUE TITLE
Non-Square pixel error

### ISSUE THREAD

**Issue by AnuPal1Hydro123** [cefect/FloodRescaler#2]
Hello everyone

I have tried to to use the QGIS script in one of my case study in Arkansas River. The resolution of DEM is 1m and the flood map resolution is 10m. However, I got an error 'non square pixels'.  

How can I fix this? 

I checked the sample datasets have DEM resolution of 4m and the flood map resolution is 32m. Do I need to resample data to this resolution?

**Comment by cefect** [comment]
Thank you for the question. 

Can you send a copy or a screen shot of the log? 

This check is performed as the algorithm has not been tested against non-square pixels. Regardless, It should be reduced from an error to a warning. 

In the meantime, Have you tried re-projecting your rasters to square pixels? (e.g., using 'Warp Reproject... and setting the resolution?).

**Comment by AnuPal1Hydro123** [comment]
![Flood_rescaler](https://github.com/cefect/FloodRescaler/assets/133904777/44e9e0ca-8e09-4114-af8e-9dd11dd3d49e)

Here is the screenshot. I will try with the reprojection to square pixels

**Comment by Pal12344** [comment]
I got this error while using the downscaling script.
![Screenshot 2023-11-03 162905](https://github.com/cefect/FloodRescaler/assets/133904777/5fa4c353-d78f-4959-b5e1-28cc7b4ca140)
Is it due to the slight  mismatch in the extent?

**Comment by AnuPal1Hydro123** [comment]
![Screenshot1](https://github.com/cefect/FloodRescaler/assets/133904777/f1353d1a-8a21-4a36-a62a-4e448200e84d)
Hi I have reprojected the pixels to 4m and 32m but still got this error. IS it due to the slight mismatch in the extent coordinates?

**Comment by cefect** [comment]
Yes, extents need to be identical… again this could probably reduced to a warning
