### ISSUE TITLE
extent mismatch

### ISSUE THREAD

**Issue by cefect** [cefect/FloodRescaler#3]
![280421745-f1353d1a-8a21-4a36-a62a-4e448200e84d](https://github.com/cefect/FloodRescaler/assets/47092034/84d75240-de33-4464-a142-4d64eeb5a344)

Hi I have reprojected the pixels to 4m and 32m but still got this error. IS it due to the slight mismatch in the extent coordinates?

_Originally posted by @Pal12344 in https://github.com/cefect/FloodRescaler/issues/2#issuecomment-1793150920_

**Comment by cefect** [comment]
@Pal12344, yes you need to ensure the rasters have the exact same extent. You should be able to do this using 'Warp Reproject... (gdal_warp)'

**Comment by Pal12344** [comment]
Hi..I used the raster calculatior and did the truncation with the extent. But after that I have got this error while using the CostGrow algorithm.
![CostGrow](https://github.com/cefect/FloodRescaler/assets/133904777/9294da0d-97d4-48a6-8b81-22c99d2e4721)

**Comment by AnuPal1Hydro123** [comment]
With the truncated raster data, the other two methods (Resample and TerrainFilter are working fine

**Comment by cefect** [comment]
Can you upload the full log file as txt?

**Comment by AnuPal1Hydro123** [comment]
[Error.txt](https://github.com/cefect/FloodRescaler/files/13270910/Error.txt)
Here it is

**Comment by cefect** [comment]
Try upgrading QGIS to 3.28.
What is the resolution of your input WSE?
Try re-projecting your DEM to a divisible integer of your coarse WSE (e.g., if your coarse is 32m re-project the DEM to 1m (instead of 0.9))

**Comment by AnuPal1Hydro123** [comment]
The resolution of INPUT WSE is 10m.
