### ISSUE TITLE
Using the downscaling script in a  binary flood map

### ISSUE THREAD

**Issue by AnuPal1Hydro123** [cefect/FloodRescaler#9]
Hi .The updated script is working fine with my datasets and thank you for your quick response. I am wondering can I use the downscaling script in a flood inundation map with two classes, flood and non-flood with two class value, 0 and 1, instead of WSE?

**Comment by cefect** [comment]
Glad to hear everything is working. As for binary inundation, no... downscaling won't be of much help as these require water levels. Instead, you'll want to check out tools like [RICorDE](https://github.com/NRCan/RICorDE/tree/main) and [FwDET](https://github.com/csdms-contrib/fwdet).

**Comment by cefect** [comment]
RICorDE and FwDET are designed to output a depths raster from a inundation polygon and a DEM... mostly targeted at remote-sensing applications. However, you can easily convert your 'binary raster' to a polygon (input), then convert the output depths raster back to a binary inundation polygon if this what you're interested in. The downscaler is mostly targeted at hydraulic modelling applications. 

Hopefully this helps
